# Generated by Django 6.0 on 2025-12-29 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='payment_status',
        ),
        migrations.AddField(
            model_name='appointment',
            name='add_to_google_calendar',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appointment',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=60),
        ),
        migrations.AddField(
            model_name='appointment',
            name='first_session',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appointment',
            name='google_calendar_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='location_details',
            field=models.CharField(blank=True, help_text='Studio address or online meeting link', max_length=255),
        ),
        migrations.AddField(
            model_name='appointment',
            name='payment_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appointment',
            name='payment_mode',
            field=models.CharField(choices=[('UPI', 'UPI'), ('CASH', 'Cash')], default='UPI', max_length=10),
        ),
        migrations.AddField(
            model_name='appointment',
            name='session_type',
            field=models.CharField(choices=[('ONLINE', 'Online'), ('OFFLINE', 'Offline (Studio)')], default='ONLINE', max_length=10),
        ),
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Confirmation'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=10),
        ),
        migrations.AddField(
            model_name='appointment',
            name='upi_id',
            field=models.CharField(blank=True, help_text='UPI ID to send payment to (if applicable)', max_length=100),
        ),
    ]
