# Generated by Django 6.0 on 2026-01-13 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_remove_appointment_payment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='payment_screenshot',
            field=models.ImageField(blank=True, help_text='Screenshot of payment confirmation', null=True, upload_to='payment_screenshots/'),
        ),
    ]
