# Generated by Django 5.2.10 on 2026-01-13 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0003_appointment_payment_screenshot'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['status', '-booked_on'], name='appointment_status_d8a92e_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['email', 'status'], name='appointment_email_4b7f7e_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['session_type', 'status'], name='appointment_session_311741_idx'),
        ),
    ]
