# Generated by Django 5.2.10 on 2026-01-14 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0004_appointment_appointment_status_d8a92e_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='therapist_name',
            field=models.CharField(blank=True, help_text='Preferred therapist or doctor name', max_length=100, null=True),
        ),
    ]
