# Generated by Django 6.0.1 on 2026-01-10 13:35

from django.db import migrations, models


def set_empty_phone_to_null(apps, schema_editor):
    Profile = apps.get_model('users', 'Profile')
    # convert empty-string phones to NULL to avoid UNIQUE constraint conflicts
    Profile.objects.filter(phone='').update(phone=None)


def reverse_set_empty_phone(apps, schema_editor):
    Profile = apps.get_model('users', 'Profile')
    # on reverse, convert NULL back to empty string
    Profile.objects.filter(phone__isnull=True).update(phone='')


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('users', '0003_googlecalendarcredential'),
    ]

    operations = [
        # First allow NULL values on the column so we can convert empty strings to NULL.
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, unique=False),
        ),
        migrations.RunPython(set_empty_phone_to_null, reverse_set_empty_phone),
        # Now add the UNIQUE constraint (NULLs are allowed and won't conflict in SQLite)
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
