# Generated by Django 6.0.1 on 2026-01-11 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_profile_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar_type',
            field=models.CharField(blank=True, choices=[('masculine', 'Masculine'), ('feminine', 'Feminine'), ('neutral', 'Neutral'), ('initials', 'Initials')], max_length=20, null=True),
        ),
    ]
