# Generated by Django 5.2.10 on 2026-01-13 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_otpverification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpverification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='otpverification',
            name='phone',
            field=models.CharField(db_index=True, max_length=15),
        ),
        migrations.AddIndex(
            model_name='otpverification',
            index=models.Index(fields=['phone', '-created_at'], name='users_otpve_phone_0a2a2a_idx'),
        ),
        migrations.AddIndex(
            model_name='otpverification',
            index=models.Index(fields=['phone', 'is_verified'], name='users_otpve_phone_76532e_idx'),
        ),
    ]
